import type { Metadata } from "next";

import "./globals.css";
import Header from "./_ui/header";
import Footer from "./_ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" w-full overflow-x-hidden relative font-manrope"}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
